name: Code Health Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: yarn install

      - name: Check Lint
        run: yarn lint

      - name: Check Code Coverage
        run: yarn test:coverage

      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./cobertura.xml
          threshold: 95
          fail: true
          publish: true
          diff: true
          diff-branch: main
          diff-storage: _xml_coverage_reports
          coverage-summary-title: "Code Coverage Summary"
