name: Code Health Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  health-check:
    permissions: write-all
    name: Code Health Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Check Lint
        run: yarn lint

      - name: Check Code Coverage
        run: yarn test:coverage

      - name: Produce the coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          annotations: none
          custom-title: "Code Coverage Summary"
